const EN_CONTRACTS_3 = [
  {
    id: "no-tricks",
    name: "No Tricks",
    description: "Avoid taking tricks.",
    scoringText: "Each trick = -4",
    maxText: "10 tricks. Round total is 40.",
    mode: "count",
    label: "Tricks taken",
    min: 0,
    max: 10,
    pointsPerUnit: -4,
  },
  {
    id: "no-hearts",
    name: "No Hearts",
    description: "Avoid taking hearts.",
    scoringText: "Each heart = -5",
    maxText: "8 hearts. Round total is 40.",
    mode: "count",
    label: "Hearts taken",
    min: 0,
    max: 8,
    pointsPerUnit: -5,
  },
  {
    id: "no-jacks",
    name: "No Jacks",
    description: "Avoid taking Jacks.",
    scoringText: "Each Jack = -10",
    maxText: "4 Jacks. Round total is 40.",
    mode: "count",
    label: "Jacks taken",
    min: 0,
    max: 4,
    pointsPerUnit: -10,
  },
  {
    id: "no-queens",
    name: "No Queens",
    description: "Avoid taking Queens.",
    scoringText: "Each Queen = -10",
    maxText: "4 Queens. Round total is 40.",
    mode: "count",
    label: "Queens taken",
    min: 0,
    max: 4,
    pointsPerUnit: -10,
  },
  {
    id: "no-last-two",
    name: "No Last Two",
    description: "Avoid taking the last two tricks.",
    scoringText: "Each last trick = -20",
    maxText: "2 scoring tricks. Round total is 40.",
    mode: "count",
    label: "Last two tricks",
    min: 0,
    max: 2,
    pointsPerUnit: -20,
  },
  {
    id: "no-king-heart",
    name: "No King of Hearts",
    description: "Avoid taking K♥.",
    scoringText: "K♥ = -40",
    maxText: "One card. Round total is 40.",
    mode: "single",
    label: "K♥ taken by",
    points: -40,
  },
  {
    id: "tricks-positive",
    name: "Tricks Positive",
    description: "Take as many tricks as possible.",
    scoringText: "Each trick = +4",
    maxText: "10 tricks. Round total is 40.",
    mode: "count",
    label: "Tricks taken",
    min: 0,
    max: 10,
    pointsPerUnit: 4,
  },
];

const ge_CONTRACTS_3 = [
  {
    id: "no-tricks",
    name: "არ აიღო კარტები",
    description: "მიზანია არ აიღო კარტები.",
    scoringText: "თითო აღება = -4",
    maxText: "10 აღება. რაუნდი 40 ქულაა.",
    mode: "count",
    label: "აღებები",
    min: 0,
    max: 10,
    pointsPerUnit: -4,
  },
  {
    id: "no-hearts",
    name: "არ აიღო გულები",
    description: "მიზანია არ აიღო გულები.",
    scoringText: "თითო გული = -5",
    maxText: "8 გული. რაუნდი 40 ქულაა.",
    mode: "count",
    label: "გულები",
    min: 0,
    max: 8,
    pointsPerUnit: -5,
  },
  {
    id: "no-jacks",
    name: "არ აიღო ვალეტები",
    description: "მიზანია არ აიღო ვალეტები.",
    scoringText: "თითო ვალეტი = -10",
    maxText: "4 ვალეტი. რაუნდი 40 ქულაა.",
    mode: "count",
    label: "ვალეტები",
    min: 0,
    max: 4,
    pointsPerUnit: -10,
  },
  {
    id: "no-queens",
    name: "არ აიღო დამები",
    description: "მიზანია არ აიღო დამები.",
    scoringText: "თითო დამა = -10",
    maxText: "4 დამა. რაუნდი 40 ქულაა.",
    mode: "count",
    label: "დამები",
    min: 0,
    max: 4,
    pointsPerUnit: -10,
  },
  {
    id: "no-last-two",
    name: "არ აიღო ბოლო ორი",
    description: "მიზანია არ აიღო ბოლო ორი კარტი.",
    scoringText: "თითო კარტის აღება = -20",
    maxText: "ბოლო ორის აღება. რაუნდი 40 ქულაა.",
    mode: "count",
    label: "ბოლო ორი",
    min: 0,
    max: 2,
    pointsPerUnit: -20,
  },
  {
    id: "no-king-heart",
    name: "არ აიღო გულის მეფე",
    description: "მიზანია არ აიღო K♥.",
    scoringText: "K♥ = -40",
    maxText: "ერთი კარტი. რაუნდი 40 ქულაა.",
    mode: "single",
    label: "K♥ აიღო",
    points: -40,
  },
  {
    id: "tricks-positive",
    name: "კარტის აღება",
    description: "მიზანია ბევრი კარტი აიღო.",
    scoringText: "თითო აღება = +4",
    maxText: "10 აღება. რაუნდი 40 ქულაა.",
    mode: "count",
    label: "კარტის აღება",
    min: 0,
    max: 10,
    pointsPerUnit: 4,
  },
];

export const LANGUAGES = {
  en: {
    ui: {
      title: "King Online",
      subtitle: "Modern table room for King card game.",
      createRoom: "Create room",
      joinRoom: "Join room",
      roomCode: "Room code",
      yourName: "Your name",
      players: "Players",
      player: "Player",
      playerCount: "Player count",
      language: "Language",
      waiting: "Waiting room",
      ready: "Ready",
      notReady: "Not ready",
      startGame: "Start game",
      dealCards: "Deal cards",
      dealing: "Dealing...",
      remove2: "Remove 2 cards",
      choose2: "Choose exactly 2 cards to remove.",
      removedCards: "Removed cards",
      chooser: "Chooser",
      turn: "Turn",
      yourTurn: "Your turn",
      table: "Table",
      cards: "cards",
      noCards: "No cards dealt yet.",
      copied: "Room code copied",
      copyCode: "Copy code",
      leaveRoom: "Leave room",
      scoreboard: "Score",
      totalScore: "Total",
      history: "History",
      chat: "Chat",
      message: "Message",
      send: "Send",
      typeMessage: "Type a message...",
      noMessages: "No messages yet.",
      chooseMode: "Choose mode",
      alreadyUsed: "Already used",
      gameFinished: "Game finished",
      finalRanking: "Final ranking",
      winner: "Winner",
      you: "you",
      close: "Close",
      selectModeFirst: "Choose a mode first.",
      waitingPlayers: "Waiting for players...",
      playCard: "Play card",
      roundDone: "Round finished",
      signOut: "Sign out",
      errors: {
        roomNotFound: "Room not found.",
        roomFull: "Room is full.",
        nameRequired: "Write your name.",
        notYourTurn: "It is not your turn.",
        mustFollowSuit: "You must follow suit.",
        heartsBlocked:
          "You cannot lead hearts in this mode unless you only have hearts.",
        chooseMode: "Choose a mode before dealing.",
      },
    },
    rules: {
      3: "3 players • 32 cards • chooser removes 2 cards",
    },
    contracts: {
      3: EN_CONTRACTS_3,
    },
  },
  ge: {
    ui: {
      title: "კინგი ონლაინ",
      subtitle: "თანამედროვე ონლაინ მაგიდა კინგისთვის.",
      createRoom: "ოთახის შექმნა",
      joinRoom: "ოთახში შესვლა",
      roomCode: "ოთახის კოდი",
      yourName: "შენი სახელი",
      players: "მოთამაშეები",
      player: "მოთამაშე",
      playerCount: "მოთამაშეების რაოდენობა",
      language: "ენა",
      waiting: "მოსაცდელი ოთახი",
      ready: "მზად ვარ",
      notReady: "არ ვარ მზად",
      startGame: "თამაშის დაწყება",
      dealCards: "კარტის დარიგება",
      dealing: "ირევა...",
      remove2: "2 კარტის ამოღება",
      choose2: "აირჩიე ზუსტად 2 კარტი ამოსაღებად.",
      removedCards: "ამოღებული კარტები",
      chooser: "ამრჩევი",
      turn: "სვლა",
      yourTurn: "შენი სვლაა",
      table: "მაგიდა",
      cards: "კარტი",
      noCards: "კარტი ჯერ არ დარიგებულა.",
      copied: "ოთახის კოდი დაკოპირდა",
      copyCode: "კოდის კოპირება",
      leaveRoom: "ოთახიდან გასვლა",
      scoreboard: "ქულა",
      totalScore: "ჯამი",
      history: "ისტორია",
      chat: "ჩატი",
      message: "შეტყობინება",
      send: "გაგზავნა",
      typeMessage: "დაწერე შეტყობინება...",
      noMessages: "შეტყობინებები ჯერ არ არის.",
      chooseMode: "რეჟიმის არჩევა",
      alreadyUsed: "გამოყენებულია",
      gameFinished: "თამაში დასრულდა",
      finalRanking: "საბოლოო რეიტინგი",
      winner: "გამარჯვებული",
      you: "შენ",
      close: "დახურვა",
      selectModeFirst: "ჯერ აირჩიე რეჟიმი.",
      waitingPlayers: "ველოდებით მოთამაშეებს...",
      playCard: "კარტის ჩასვლა",
      roundDone: "რაუნდი დასრულდა",
      signOut: "გამოსვლა",
      errors: {
        roomNotFound: "ოთახი ვერ მოიძებნა.",
        roomFull: "ოთახი სავსეა.",
        nameRequired: "ჩაწერე სახელი.",
        notYourTurn: "ახლა შენი სვლა არ არის.",
        mustFollowSuit: "ფერი უნდა მიყვე.",
        heartsBlocked:
          "ამ რეჟიმში გულით დაწყება არ შეიძლება, თუ მარტო გულები არ გაქვს.",
        chooseMode: "დარიგებამდე აირჩიე რეჟიმი.",
      },
    },
    rules: {
      3: "3 მოთამაშე • 32 კარტი • ამრჩევი 2 კარტს აგდებს",
    },
    contracts: {
      3: ge_CONTRACTS_3,
    },
  },
};
